FROM phpmyadmin/phpmyadmin:latest

ENV PMA_HOST=mysql
ENV PMA_PORT=3306
ENV PMA_USER=root
ENV PMA_PASSWORD=""
ENV MYSQL_ROOT_PASSWORD=""

# These will be overridden by Railway environment variables
ENV PMA_ARBITRARY=1
