version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/dorm-mart"
    schedule:
      interval: "weekly"
    target-branch: "railway-deployment"

  - package-ecosystem: "composer"
    directory: "/dorm-mart"
    schedule:
      interval: "weekly"
    target-branch: "railway-deployment"
