<?php

declare(strict_types=1);

require_once __DIR__ . '/../helpers/api_bootstrap.php';
require_once __DIR__ . '/../helpers/request.php';
require_once __DIR__ . '/../auth/auth_handle.php';
require_once __DIR__ . '/../database/db_connect.php';
require_once __DIR__ . '/../helpers/moderation.php';

init_json_endpoint('POST');
$reporterId = require_login();
$input = json_request_body();
require_csrf_token($input['csrf_token'] ?? null);

$messageId = request_int($input, 'message_id');
$reasonValue = $input['reason'] ?? 'Inappropriate or unsafe content';
$reason = is_string($reasonValue) ? trim($reasonValue) : '';
$reasonLength = function_exists('mb_strlen') ? mb_strlen($reason, 'UTF-8') : strlen($reason);
if ($messageId <= 0 || $reason === '' || $reasonLength > 255) {
    json_response(['success' => false, 'error' => 'Invalid report'], 400);
}

moderation_require_report_quota('report_message', $reporterId);

try {
    $conn = db();
    $conn->set_charset('utf8mb4');
    $stmt = $conn->prepare(
        'SELECT m.sender_id, m.metadata, m.deleted_at
           FROM messages m
           JOIN conversations c ON c.conv_id = m.conv_id
          WHERE m.message_id = ? AND (c.user1_id = ? OR c.user2_id = ?)
          LIMIT 1'
    );
    $stmt->bind_param('iii', $messageId, $reporterId, $reporterId);
    $stmt->execute();
    $message = $stmt->get_result()->fetch_assoc();
    $stmt->close();

    if (!$message) json_response(['success' => false, 'error' => 'Message not found'], 404);
    $reportedUserId = (int)($message['sender_id'] ?? 0);
    // System cards are generated by Dorm Mart, and deleted messages have no
    // content left to review; the chat UI hides Report on both.
    $isSystemCard = $message['metadata'] !== null && $message['metadata'] !== '';
    if ($reportedUserId <= 0 || $reportedUserId === $reporterId || $isSystemCard || $message['deleted_at'] !== null) {
        json_response(['success' => false, 'error' => 'You cannot report this message'], 409);
    }

    $stmt = $conn->prepare(
        // One report per person per message. Reporting again updates an open
        // report; once a moderator has decided, the decision stands (it used to
        // reopen dismissed reports, letting one user re-queue them forever).
        "INSERT INTO message_reports (message_id, reporter_id, reported_user_id, reason)
         VALUES (?, ?, ?, ?)
         ON DUPLICATE KEY UPDATE report_id = LAST_INSERT_ID(report_id),
                                 reason = IF(status = 'open', VALUES(reason), reason)"
    );
    $stmt->bind_param('iiis', $messageId, $reporterId, $reportedUserId, $reason);
    $stmt->execute();
    $reportId = (int)$conn->insert_id;
    $stmt->close();

    json_response(['success' => true, 'report_id' => $reportId, 'message_id' => $messageId]);
} catch (Throwable $e) {
    error_log('message report error: ' . $e->getMessage());
    json_response(['success' => false, 'error' => 'Server error'], 500);
}
